<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countrys')->insert(['country' => 'Afghanistan', 'flag' => 'af.png']);
        DB::table('countrys')->insert(['country' => 'Albania', 'flag' => 'al.png']);
        DB::table('countrys')->insert(['country' => 'Algeria', 'flag' => 'dz.png']);
        DB::table('countrys')->insert(['country' => 'Andorra', 'flag' => 'ad.png']);
        DB::table('countrys')->insert(['country' => 'Angola', 'flag' => 'ao.png']);
        DB::table('countrys')->insert(['country' => 'Antigua and Barbuda', 'flag' => 'ag.png']);
        DB::table('countrys')->insert(['country' => 'Argentina', 'flag' => 'ar.png']);
        DB::table('countrys')->insert(['country' => 'Armenia', 'flag' => 'am.png']);
        DB::table('countrys')->insert(['country' => 'Australia', 'flag' => 'au.png']);
        DB::table('countrys')->insert(['country' => 'Austria', 'flag' => 'at.png']);
        DB::table('countrys')->insert(['country' => 'Azerbaijan', 'flag' => 'az.png']);
        DB::table('countrys')->insert(['country' => 'Bahamas', 'flag' => 'bs.png']);
        DB::table('countrys')->insert(['country' => 'Bahrain', 'flag' => 'bh.png']);
        DB::table('countrys')->insert(['country' => 'Bangladesh', 'flag' => 'bd.png']);
        DB::table('countrys')->insert(['country' => 'Barbados', 'flag' => 'bb.png']);
        DB::table('countrys')->insert(['country' => 'Belarus', 'flag' => 'by.png']);
        DB::table('countrys')->insert(['country' => 'Belgium', 'flag' => 'be.png']);
        DB::table('countrys')->insert(['country' => 'Belize', 'flag' => 'bz.png']);
        DB::table('countrys')->insert(['country' => 'Benin', 'flag' => 'bj.png']);
        DB::table('countrys')->insert(['country' => 'Bhutan', 'flag' => 'bt.png']);
        DB::table('countrys')->insert(['country' => 'Bolivia', 'flag' => 'bo.png']);
        DB::table('countrys')->insert(['country' => 'Bosnia and Herzegovina', 'flag' => 'ba.png']);
        DB::table('countrys')->insert(['country' => 'Botswana', 'flag' => 'bw.png']);
        DB::table('countrys')->insert(['country' => 'Brazil', 'flag' => 'br.png']);
        DB::table('countrys')->insert(['country' => 'Brunei', 'flag' => 'bn.png']);
        DB::table('countrys')->insert(['country' => 'Bulgaria', 'flag' => 'bg.png']);
        DB::table('countrys')->insert(['country' => 'Burkina Faso', 'flag' => 'bf.png']);
        DB::table('countrys')->insert(['country' => 'Burundi', 'flag' => 'bi.png']);
        DB::table('countrys')->insert(['country' => 'Cambodia', 'flag' => 'kh.png']);
        DB::table('countrys')->insert(['country' => 'Cameroon', 'flag' => 'cm.png']);
        DB::table('countrys')->insert(['country' => 'Canada', 'flag' => 'ca.png']);
        DB::table('countrys')->insert(['country' => 'Cabo Verde', 'flag' => 'cv.png']);
        DB::table('countrys')->insert(['country' => 'Central African Republic', 'flag' => 'cf.png']);
        DB::table('countrys')->insert(['country' => 'Chad', 'flag' => 'td.png']);
        DB::table('countrys')->insert(['country' => 'Chile', 'flag' => 'cl.png']);
        DB::table('countrys')->insert(['country' => 'Colombia', 'flag' => 'co.png']);
        DB::table('countrys')->insert(['country' => 'Comoros', 'flag' => 'km.png']);
        DB::table('countrys')->insert(['country' => 'Cook Islands', 'flag' => 'ck.png']);
        DB::table('countrys')->insert(['country' => 'Costa Rica', 'flag' => 'cr.png']);
        DB::table('countrys')->insert(['country' => 'Cote d\'Ivoire', 'flag' => 'ci.png']);
        DB::table('countrys')->insert(['country' => 'Croatia', 'flag' => 'hr.png']);
        DB::table('countrys')->insert(['country' => 'Cuba', 'flag' => 'cu.png']);
        DB::table('countrys')->insert(['country' => 'Cyprus', 'flag' => 'cy.png']);
        DB::table('countrys')->insert(['country' => 'Czechia', 'flag' => 'cz.png']);
        DB::table('countrys')->insert(['country' => 'Congo', 'flag' => 'cg.png']);
        DB::table('countrys')->insert(['country' => 'Denmark', 'flag' => 'dk.png']);
        DB::table('countrys')->insert(['country' => 'Djibouti', 'flag' => 'dj.png']);
        DB::table('countrys')->insert(['country' => 'Dominica', 'flag' => 'dm.png']);
        DB::table('countrys')->insert(['country' => 'Dominican Republic', 'flag' => 'do.png']);
        DB::table('countrys')->insert(['country' => 'East Timor', 'flag' => 'tl.png']);
        DB::table('countrys')->insert(['country' => 'Ecuador', 'flag' => 'ec.png']);
        DB::table('countrys')->insert(['country' => 'Egypt', 'flag' => 'eg.png']);
        DB::table('countrys')->insert(['country' => 'El Salvador', 'flag' => 'sv.png']);
        DB::table('countrys')->insert(['country' => 'Equatorial Guinea', 'flag' => 'gq.png']);
        DB::table('countrys')->insert(['country' => 'Eritrea', 'flag' => 'er.png']);
        DB::table('countrys')->insert(['country' => 'Estonia', 'flag' => 'ee.png']);
        DB::table('countrys')->insert(['country' => 'Ethiopia', 'flag' => 'et.png']);
        DB::table('countrys')->insert(['country' => 'Fiji', 'flag' => 'fj.png']);
        DB::table('countrys')->insert(['country' => 'Finland', 'flag' => 'fi.png']);
        DB::table('countrys')->insert(['country' => 'France', 'flag' => 'fr.png']);
        DB::table('countrys')->insert(['country' => 'Gabon', 'flag' => 'ga.png']);
        DB::table('countrys')->insert(['country' => 'Gambia', 'flag' => 'gm.png']);
        DB::table('countrys')->insert(['country' => 'Georgia', 'flag' => 'ge.png']);
        DB::table('countrys')->insert(['country' => 'Germany', 'flag' => 'de.png']);
        DB::table('countrys')->insert(['country' => 'Ghana', 'flag' => 'gh.png']);
        DB::table('countrys')->insert(['country' => 'Greece', 'flag' => 'gr.png']);
        DB::table('countrys')->insert(['country' => 'Grenada', 'flag' => 'gd.png']);
        DB::table('countrys')->insert(['country' => 'Guatemala', 'flag' => 'gt.png']);
        DB::table('countrys')->insert(['country' => 'Guinea', 'flag' => 'gn.png']);
        DB::table('countrys')->insert(['country' => 'Guinea-Bissau', 'flag' => 'gw.png']);
        DB::table('countrys')->insert(['country' => 'Guyana', 'flag' => 'gy.png']);
        DB::table('countrys')->insert(['country' => 'Haiti', 'flag' => 'ht.png']);
        DB::table('countrys')->insert(['country' => 'Honduras', 'flag' => 'hn.png']);
        DB::table('countrys')->insert(['country' => 'Hungary', 'flag' => 'hu.png']);
        DB::table('countrys')->insert(['country' => 'Iceland', 'flag' => 'is.png']);
        DB::table('countrys')->insert(['country' => 'India', 'flag' => 'in.png']);
        DB::table('countrys')->insert(['country' => 'Indonesia', 'flag' => 'id.png']);
        DB::table('countrys')->insert(['country' => 'Iran', 'flag' => 'ir.png']);
        DB::table('countrys')->insert(['country' => 'Iraq', 'flag' => 'iq.png']);
        DB::table('countrys')->insert(['country' => 'Ireland', 'flag' => 'ie.png']);
        DB::table('countrys')->insert(['country' => 'Israel', 'flag' => 'il.png']);
        DB::table('countrys')->insert(['country' => 'Italy', 'flag' => 'it.png']);
        DB::table('countrys')->insert(['country' => 'Jamaica', 'flag' => 'jm.png']);
        DB::table('countrys')->insert(['country' => 'Japan', 'flag' => 'jp.png']);
        DB::table('countrys')->insert(['country' => 'Jordan', 'flag' => 'jo.png']);
        DB::table('countrys')->insert(['country' => 'Kazakhstan', 'flag' => 'kz.png']);
        DB::table('countrys')->insert(['country' => 'Kenya', 'flag' => 'ke.png']);
        DB::table('countrys')->insert(['country' => 'Kiribati', 'flag' => 'ki.png']);
        DB::table('countrys')->insert(['country' => 'Kuwait', 'flag' => 'kw.png']);
        DB::table('countrys')->insert(['country' => 'Kyrgyzstan', 'flag' => 'kg.png']);
        DB::table('countrys')->insert(['country' => 'Laos', 'flag' => 'la.png']);
        DB::table('countrys')->insert(['country' => 'Latvia', 'flag' => 'lv.png']);
        DB::table('countrys')->insert(['country' => 'Lebanon', 'flag' => 'lb.png']);
        DB::table('countrys')->insert(['country' => 'Lesotho', 'flag' => 'ls.png']);
        DB::table('countrys')->insert(['country' => 'Liberia', 'flag' => 'lr.png']);
        DB::table('countrys')->insert(['country' => 'Libya', 'flag' => 'ly.png']);
        DB::table('countrys')->insert(['country' => 'Liechtenstein', 'flag' => 'li.png']);
        DB::table('countrys')->insert(['country' => 'Lithuania', 'flag' => 'lt.png']);
        DB::table('countrys')->insert(['country' => 'Luxembourg', 'flag' => 'lu.png']);
        DB::table('countrys')->insert(['country' => 'Macedonia', 'flag' => 'mk.png']);
        DB::table('countrys')->insert(['country' => 'Madagascar', 'flag' => 'mg.png']);
        DB::table('countrys')->insert(['country' => 'Malawi', 'flag' => 'mw.png']);
        DB::table('countrys')->insert(['country' => 'Malaysia', 'flag' => 'my.png']);
        DB::table('countrys')->insert(['country' => 'Maldives', 'flag' => 'mv.png']);
        DB::table('countrys')->insert(['country' => 'Mali', 'flag' => 'ml.png']);
        DB::table('countrys')->insert(['country' => 'Malta', 'flag' => 'mt.png']);
        DB::table('countrys')->insert(['country' => 'Marshall Islands', 'flag' => 'mh.png']);
        DB::table('countrys')->insert(['country' => 'Mauritania', 'flag' => 'mr.png']);
        DB::table('countrys')->insert(['country' => 'Mauritius', 'flag' => 'mu.png']);
        DB::table('countrys')->insert(['country' => 'Mexico', 'flag' => 'mx.png']);
        DB::table('countrys')->insert(['country' => 'Micronesia', 'flag' => 'fm.png']);
        DB::table('countrys')->insert(['country' => 'Moldova', 'flag' => 'md.png']);
        DB::table('countrys')->insert(['country' => 'Monaco', 'flag' => 'mc.png']);
        DB::table('countrys')->insert(['country' => 'Mongolia', 'flag' => 'mn.png']);
        DB::table('countrys')->insert(['country' => 'Montenegro', 'flag' => 'me.png']);
        DB::table('countrys')->insert(['country' => 'Morocco', 'flag' => 'ma.png']);
        DB::table('countrys')->insert(['country' => 'Mozambique', 'flag' => 'mz.png']);
        DB::table('countrys')->insert(['country' => 'Myanmar', 'flag' => 'mm.png']);
        DB::table('countrys')->insert(['country' => 'Namibia', 'flag' => 'na.png']);
        DB::table('countrys')->insert(['country' => 'Nauru', 'flag' => 'nr.png']);
        DB::table('countrys')->insert(['country' => 'Nepal', 'flag' => 'np.png']);
        DB::table('countrys')->insert(['country' => 'Netherlands', 'flag' => 'nl.png']);
        DB::table('countrys')->insert(['country' => 'New Zealand', 'flag' => 'nz.png']);
        DB::table('countrys')->insert(['country' => 'Nicaragua', 'flag' => 'ni.png']);
        DB::table('countrys')->insert(['country' => 'Niger', 'flag' => 'ne.png']);
        DB::table('countrys')->insert(['country' => 'Nigeria', 'flag' => 'ng.png']);
        DB::table('countrys')->insert(['country' => 'Niue', 'flag' => 'nu.png']);
        DB::table('countrys')->insert(['country' => 'North Korea', 'flag' => 'kp.png']);
        DB::table('countrys')->insert(['country' => 'Norway', 'flag' => 'no.png']);
        DB::table('countrys')->insert(['country' => 'Oman', 'flag' => 'om.png']);
        DB::table('countrys')->insert(['country' => 'Pakistan', 'flag' => 'pk.png']);
        DB::table('countrys')->insert(['country' => 'Palau', 'flag' => 'pw.png']);
        DB::table('countrys')->insert(['country' => 'Panama', 'flag' => 'pa.png']);
        DB::table('countrys')->insert(['country' => 'Papua New Guinea', 'flag' => 'pg.png']);
        DB::table('countrys')->insert(['country' => 'Paraguay', 'flag' => 'py.png']);
        DB::table('countrys')->insert(['country' => 'China', 'flag' => 'cn.png']);
        DB::table('countrys')->insert(['country' => 'Peru', 'flag' => 'pe.png']);
        DB::table('countrys')->insert(['country' => 'Philippines', 'flag' => 'ph.png']);
        DB::table('countrys')->insert(['country' => 'Poland', 'flag' => 'pl.png']);
        DB::table('countrys')->insert(['country' => 'Portugal', 'flag' => 'pt.png']);
        DB::table('countrys')->insert(['country' => 'Qatar', 'flag' => 'qa.png']);
        DB::table('countrys')->insert(['country' => 'Romania', 'flag' => 'ro.png']);
        DB::table('countrys')->insert(['country' => 'Russia', 'flag' => 'ru.png']);
        DB::table('countrys')->insert(['country' => 'Rwanda', 'flag' => 'rw.png']);
        DB::table('countrys')->insert(['country' => 'Saint Kitts and Nevis', 'flag' => 'kn.png']);
        DB::table('countrys')->insert(['country' => 'Saint Lucia', 'flag' => 'lc.png']);
        DB::table('countrys')->insert(['country' => 'Samoa', 'flag' => 'ws.png']);
        DB::table('countrys')->insert(['country' => 'San Marino', 'flag' => 'sm.png']);
        DB::table('countrys')->insert(['country' => 'Saudi Arabia', 'flag' => 'sa.png']);
        DB::table('countrys')->insert(['country' => 'Senegal', 'flag' => 'sn.png']);
        DB::table('countrys')->insert(['country' => 'Serbia', 'flag' => 'rs.png']);
        DB::table('countrys')->insert(['country' => 'Seychelles', 'flag' => 'sc.png']);
        DB::table('countrys')->insert(['country' => 'Sierra Leone', 'flag' => 'sl.png']);
        DB::table('countrys')->insert(['country' => 'Singapore', 'flag' => 'sg.png']);
        DB::table('countrys')->insert(['country' => 'Slovakia', 'flag' => 'sk.png']);
        DB::table('countrys')->insert(['country' => 'Slovenia', 'flag' => 'si.png']);
        DB::table('countrys')->insert(['country' => 'Solomon Islands', 'flag' => 'sb.png']);
        DB::table('countrys')->insert(['country' => 'Somalia', 'flag' => 'so.png']);
        DB::table('countrys')->insert(['country' => 'South Africa', 'flag' => 'za.png']);
        DB::table('countrys')->insert(['country' => 'South Korea', 'flag' => 'kr.png']);
        DB::table('countrys')->insert(['country' => 'South Sudan', 'flag' => 'ss.png']);
        DB::table('countrys')->insert(['country' => 'Spain', 'flag' => 'es.png']);
        DB::table('countrys')->insert(['country' => 'Sri Lanka', 'flag' => 'lk.png']);
        DB::table('countrys')->insert(['country' => 'Sudan', 'flag' => 'sd.png']);
        DB::table('countrys')->insert(['country' => 'Suriname', 'flag' => 'sr.png']);
        DB::table('countrys')->insert(['country' => 'Swaziland', 'flag' => 'ch.png']);
        DB::table('countrys')->insert(['country' => 'Sweden', 'flag' => 'se.png']);
        DB::table('countrys')->insert(['country' => 'Switzerland', 'flag' => 'ch.png']);
        DB::table('countrys')->insert(['country' => 'Syria', 'flag' => 'sy.png']);
        DB::table('countrys')->insert(['country' => 'Tajikistan', 'flag' => 'tj.png']);
        DB::table('countrys')->insert(['country' => 'Tanzania', 'flag' => 'tz.png']);
        DB::table('countrys')->insert(['country' => 'Thailand', 'flag' => 'th.png']);
        DB::table('countrys')->insert(['country' => 'Togo', 'flag' => 'tg.png']);
        DB::table('countrys')->insert(['country' => 'Tonga', 'flag' => 'to.png']);
        DB::table('countrys')->insert(['country' => 'Tunisia', 'flag' => 'tn.png']);
        DB::table('countrys')->insert(['country' => 'Turkey', 'flag' => 'tr.png']);
        DB::table('countrys')->insert(['country' => 'Turkmenistan', 'flag' => 'tm.png']);
        DB::table('countrys')->insert(['country' => 'Tuvalu', 'flag' => 'tv.png']);
        DB::table('countrys')->insert(['country' => 'Uganda', 'flag' => 'ug.png']);
        DB::table('countrys')->insert(['country' => 'Ukraine', 'flag' => 'ua.png']);
        DB::table('countrys')->insert(['country' => 'United Arab Emirates', 'flag' => 'ae.png']);
        DB::table('countrys')->insert(['country' => 'United Kingdom', 'flag' => 'gb.png']);
        DB::table('countrys')->insert(['country' => 'United States', 'flag' => 'us.png']);
        DB::table('countrys')->insert(['country' => 'Uruguay', 'flag' => 'uy.png']);
        DB::table('countrys')->insert(['country' => 'Uzbekistan', 'flag' => 'uz.png']);
        DB::table('countrys')->insert(['country' => 'Vanuatu', 'flag' => 'vu.png']);
        DB::table('countrys')->insert(['country' => 'Venezuela', 'flag' => 've.png']);
        DB::table('countrys')->insert(['country' => 'Vietnam', 'flag' => 'vn.png']);
        DB::table('countrys')->insert(['country' => 'Yemen', 'flag' => 'ye.png']);
        DB::table('countrys')->insert(['country' => 'Zambia', 'flag' => 'zm.png']);
        DB::table('countrys')->insert(['country' => 'Zimbabwe', 'flag' => 'zw.png']);
    }
}
