<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countrys')->insert(['country' => 'Afghanistan', 'flag' => 'afghanistan.png']);
        DB::table('countrys')->insert(['country' => 'Albania', 'flag' => 'albania.png']);
        DB::table('countrys')->insert(['country' => 'Algeria', 'flag' => 'algeria.png']);
        DB::table('countrys')->insert(['country' => 'Andorra', 'flag' => 'andorra.png']);
        DB::table('countrys')->insert(['country' => 'Angola', 'flag' => 'angola.png']);
        DB::table('countrys')->insert(['country' => 'Antigua and Barbuda', 'flag' => 'antigua_and_barbuda.png']);
        DB::table('countrys')->insert(['country' => 'Argentina', 'flag' => 'argentina.png']);
        DB::table('countrys')->insert(['country' => 'Armenia', 'flag' => 'armenia.png']);
        DB::table('countrys')->insert(['country' => 'Australia', 'flag' => 'australia.png']);
        DB::table('countrys')->insert(['country' => 'Austria', 'flag' => 'austria.png']);
        DB::table('countrys')->insert(['country' => 'Azerbaijan', 'flag' => 'azerbaijan.png']);
        DB::table('countrys')->insert(['country' => 'Bahamas', 'flag' => 'bahamas.png']);
        DB::table('countrys')->insert(['country' => 'Bahrain', 'flag' => 'bahrain.png']);
        DB::table('countrys')->insert(['country' => 'Bangladesh', 'flag' => 'bangladesh.png']);
        DB::table('countrys')->insert(['country' => 'Barbados', 'flag' => 'barbados.png']);
        DB::table('countrys')->insert(['country' => 'Belarus', 'flag' => 'belarus.png']);
        DB::table('countrys')->insert(['country' => 'Belgium', 'flag' => 'belgium.png']);
        DB::table('countrys')->insert(['country' => 'Belize', 'flag' => 'belize.png']);
        DB::table('countrys')->insert(['country' => 'Benin', 'flag' => 'benin.png']);
        DB::table('countrys')->insert(['country' => 'Bhutan', 'flag' => 'bhutan.png']);
        DB::table('countrys')->insert(['country' => 'Bolivia', 'flag' => 'bolivia.png']);
        DB::table('countrys')->insert(['country' => 'Bosnia and Herzegovina', 'flag' => 'bosnia_and_herzegovina.png']);
        DB::table('countrys')->insert(['country' => 'Botswana', 'flag' => 'botswana.png']);
        DB::table('countrys')->insert(['country' => 'Brazil', 'flag' => 'brazil.png']);
        DB::table('countrys')->insert(['country' => 'Brunei', 'flag' => 'brunei.png']);
        DB::table('countrys')->insert(['country' => 'Bulgaria', 'flag' => 'bulgaria.png']);
        DB::table('countrys')->insert(['country' => 'Burkina Faso', 'flag' => 'burkina_faso.png']);
        DB::table('countrys')->insert(['country' => 'Burundi', 'flag' => 'burundi.png']);
        DB::table('countrys')->insert(['country' => 'Cambodia', 'flag' => 'cambodia.png']);
        DB::table('countrys')->insert(['country' => 'Cameroon', 'flag' => 'cameroon.png']);
        DB::table('countrys')->insert(['country' => 'Canada', 'flag' => 'canada.png']);
        DB::table('countrys')->insert(['country' => 'Cape Verde', 'flag' => 'cape_verde.png']);
        DB::table('countrys')->insert(['country' => 'Central African Republic', 'flag' => 'the_central_african_republic.png']);
        DB::table('countrys')->insert(['country' => 'Chad', 'flag' => 'chad.png']);
        DB::table('countrys')->insert(['country' => 'Chile', 'flag' => 'chile.png']);
        DB::table('countrys')->insert(['country' => 'Colombia', 'flag' => 'colombia.png']);
        DB::table('countrys')->insert(['country' => 'Comoros', 'flag' => 'the_comoros.png']);
        DB::table('countrys')->insert(['country' => 'Cook Islands', 'flag' => 'cook_islands.png']);
        DB::table('countrys')->insert(['country' => 'Costa Rica', 'flag' => 'costa_rica.png']);
        DB::table('countrys')->insert(['country' => 'Cote d\'Ivoire', 'flag' => 'cote_dIvoire.png']);
        DB::table('countrys')->insert(['country' => 'Croatia', 'flag' => 'croatia.png']);
        DB::table('countrys')->insert(['country' => 'Cuba', 'flag' => 'cuba.png']);
        DB::table('countrys')->insert(['country' => 'Cyprus', 'flag' => 'cyprus.png']);
        DB::table('countrys')->insert(['country' => 'Czech Republic', 'flag' => 'czech_republic.png']);
        DB::table('countrys')->insert(['country' => 'Democratic Republic of the Congo', 'flag' => 'congo.png']);
        DB::table('countrys')->insert(['country' => 'Denmark', 'flag' => 'denmark.png']);
        DB::table('countrys')->insert(['country' => 'Djibouti', 'flag' => 'djibouti.png']);
        DB::table('countrys')->insert(['country' => 'Dominica', 'flag' => 'dominica.png']);
        DB::table('countrys')->insert(['country' => 'Dominican Republic', 'flag' => 'dominican_republic.png']);
        DB::table('countrys')->insert(['country' => 'East Timor', 'flag' => 'east_timor.png']);
        DB::table('countrys')->insert(['country' => 'Ecuador', 'flag' => 'ecuador.png']);
        DB::table('countrys')->insert(['country' => 'Egypt', 'flag' => 'egypt.png']);
        DB::table('countrys')->insert(['country' => 'El Salvador', 'flag' => 'el_salvador.png']);
        DB::table('countrys')->insert(['country' => 'Equatorial Guinea', 'flag' => 'equatorial_guinea.png']);
        DB::table('countrys')->insert(['country' => 'Eritrea', 'flag' => 'eritrea.png']);
        DB::table('countrys')->insert(['country' => 'Estonia', 'flag' => 'estonia.png']);
        DB::table('countrys')->insert(['country' => 'Ethiopia', 'flag' => 'ethiopia.png']);
        DB::table('countrys')->insert(['country' => 'Fiji', 'flag' => 'fiji.png']);
        DB::table('countrys')->insert(['country' => 'Finland', 'flag' => 'finland.png']);
        DB::table('countrys')->insert(['country' => 'France', 'flag' => 'france.png']);
        DB::table('countrys')->insert(['country' => 'Gabon', 'flag' => 'gabon.png']);
        DB::table('countrys')->insert(['country' => 'Gambia', 'flag' => 'gambia.png']);
        DB::table('countrys')->insert(['country' => 'Georgia', 'flag' => 'georgia.png']);
        DB::table('countrys')->insert(['country' => 'Germany', 'flag' => 'germany.png']);
        DB::table('countrys')->insert(['country' => 'Ghana', 'flag' => 'ghana.png']);
        DB::table('countrys')->insert(['country' => 'Greece', 'flag' => 'greece.png']);
        DB::table('countrys')->insert(['country' => 'Grenada', 'flag' => 'grenada.png']);
        DB::table('countrys')->insert(['country' => 'Guatemala', 'flag' => 'guatemala.png']);
        DB::table('countrys')->insert(['country' => 'Guinea', 'flag' => 'guinea.png']);
        DB::table('countrys')->insert(['country' => 'Guinea-Bissau', 'flag' => 'guinea-bissau.png']);
        DB::table('countrys')->insert(['country' => 'Guyana', 'flag' => 'guyana.png']);
        DB::table('countrys')->insert(['country' => 'Haiti', 'flag' => 'haiti.png']);
        DB::table('countrys')->insert(['country' => 'Honduras', 'flag' => 'honduras.png']);
        DB::table('countrys')->insert(['country' => 'Hungary', 'flag' => 'hungary.png']);
        DB::table('countrys')->insert(['country' => 'Iceland', 'flag' => 'iceland.png']);
        DB::table('countrys')->insert(['country' => 'India', 'flag' => 'india.png']);
        DB::table('countrys')->insert(['country' => 'Indonesia', 'flag' => 'indonesia.png']);
        DB::table('countrys')->insert(['country' => 'Iran', 'flag' => 'iran.png']);
        DB::table('countrys')->insert(['country' => 'Iraq', 'flag' => 'iraq.png']);
        DB::table('countrys')->insert(['country' => 'Ireland', 'flag' => 'ireland.png']);
        DB::table('countrys')->insert(['country' => 'Israel', 'flag' => 'israel.png']);
        DB::table('countrys')->insert(['country' => 'Italy', 'flag' => 'italy.png']);
        DB::table('countrys')->insert(['country' => 'Jamaica', 'flag' => 'jamaica.png']);
        DB::table('countrys')->insert(['country' => 'Japan', 'flag' => 'japan.png']);
        DB::table('countrys')->insert(['country' => 'Jordan', 'flag' => 'jordan.png']);
        DB::table('countrys')->insert(['country' => 'Kazakhstan', 'flag' => 'kazakhstan.png']);
        DB::table('countrys')->insert(['country' => 'Kenya', 'flag' => 'kenya.png']);
        DB::table('countrys')->insert(['country' => 'Kiribati', 'flag' => 'kiribati.png']);
        DB::table('countrys')->insert(['country' => 'Kosovo', 'flag' => 'kosovo.png']);
        DB::table('countrys')->insert(['country' => 'Kuwait', 'flag' => 'kuwait.png']);
        DB::table('countrys')->insert(['country' => 'Kyrgyzstan', 'flag' => 'kyrgyzstan.png']);
        DB::table('countrys')->insert(['country' => 'Laos', 'flag' => 'laos.png']);
        DB::table('countrys')->insert(['country' => 'Latvia', 'flag' => 'latvia.png']);
        DB::table('countrys')->insert(['country' => 'Lebanon', 'flag' => 'lebanon.png']);
        DB::table('countrys')->insert(['country' => 'Lesotho', 'flag' => 'lesotho.png']);
        DB::table('countrys')->insert(['country' => 'Liberia', 'flag' => 'liberia.png']);
        DB::table('countrys')->insert(['country' => 'Libya', 'flag' => 'libya.png']);
        DB::table('countrys')->insert(['country' => 'Liechtenstein', 'flag' => 'liechtenstein.png']);
        DB::table('countrys')->insert(['country' => 'Lithuania', 'flag' => 'lithuania.png']);
        DB::table('countrys')->insert(['country' => 'Luxembourg', 'flag' => 'luxembourg.png']);
        DB::table('countrys')->insert(['country' => 'Macedonia', 'flag' => 'macedonia.png']);
        DB::table('countrys')->insert(['country' => 'Madagascar', 'flag' => 'madagascar.png']);
        DB::table('countrys')->insert(['country' => 'Malawi', 'flag' => 'malawi.png']);
        DB::table('countrys')->insert(['country' => 'Malaysia', 'flag' => 'malaysia.png']);
        DB::table('countrys')->insert(['country' => 'Maldives', 'flag' => 'maldives.png']);
        DB::table('countrys')->insert(['country' => 'Mali', 'flag' => 'mali.png']);
        DB::table('countrys')->insert(['country' => 'Malta', 'flag' => 'malta.png']);
        DB::table('countrys')->insert(['country' => 'Marshall Islands', 'flag' => 'marshall_islands.png']);
        DB::table('countrys')->insert(['country' => 'Mauritania', 'flag' => 'mauritania.png']);
        DB::table('countrys')->insert(['country' => 'Mauritius', 'flag' => 'mauritius.png']);
        DB::table('countrys')->insert(['country' => 'Mexico', 'flag' => 'mexico.png']);
        DB::table('countrys')->insert(['country' => 'Micronesia', 'flag' => 'micronesia.png']);
        DB::table('countrys')->insert(['country' => 'Moldova', 'flag' => 'moldova.png']);
        DB::table('countrys')->insert(['country' => 'Monaco', 'flag' => 'monaco.png']);
        DB::table('countrys')->insert(['country' => 'Mongolia', 'flag' => 'mongolia.png']);
        DB::table('countrys')->insert(['country' => 'Montenegro', 'flag' => 'montenegro.png']);
        DB::table('countrys')->insert(['country' => 'Morocco', 'flag' => 'morocco.png']);
        DB::table('countrys')->insert(['country' => 'Mozambique', 'flag' => 'mozambique.png']);
        DB::table('countrys')->insert(['country' => 'Myanmar', 'flag' => 'myanmar.png']);
        DB::table('countrys')->insert(['country' => 'Namibia', 'flag' => 'namibia.png']);
        DB::table('countrys')->insert(['country' => 'Nauru', 'flag' => 'nauru.png']);
        DB::table('countrys')->insert(['country' => 'Nepal', 'flag' => 'nepal.png']);
        DB::table('countrys')->insert(['country' => 'Netherlands', 'flag' => 'netherlands.png']);
        DB::table('countrys')->insert(['country' => 'New Zealand', 'flag' => 'new_zealand.png']);
        DB::table('countrys')->insert(['country' => 'Nicaragua', 'flag' => 'nicaragua.png']);
        DB::table('countrys')->insert(['country' => 'Niger', 'flag' => 'niger.png']);
        DB::table('countrys')->insert(['country' => 'Nigeria', 'flag' => 'nigeria.png']);
        DB::table('countrys')->insert(['country' => 'Niue', 'flag' => 'niue.png']);
        DB::table('countrys')->insert(['country' => 'North Korea', 'flag' => 'north_korea.png']);
        DB::table('countrys')->insert(['country' => 'Norway', 'flag' => 'norway.png']);
        DB::table('countrys')->insert(['country' => 'Oman', 'flag' => 'oman.png']);
        DB::table('countrys')->insert(['country' => 'Pakistan', 'flag' => 'pakistan.png']);
        DB::table('countrys')->insert(['country' => 'Palau', 'flag' => 'palau.png']);
        DB::table('countrys')->insert(['country' => 'Panama', 'flag' => 'panama.png']);
        DB::table('countrys')->insert(['country' => 'Papua New Guinea', 'flag' => 'papua_new_guinea.png']);
        DB::table('countrys')->insert(['country' => 'Paraguay', 'flag' => 'paraguay.png']);
        DB::table('countrys')->insert(['country' => 'China', 'flag' => 'china.png']);
        DB::table('countrys')->insert(['country' => 'Peru', 'flag' => 'peru.png']);
        DB::table('countrys')->insert(['country' => 'Philippines', 'flag' => 'philippines.png']);
        DB::table('countrys')->insert(['country' => 'Poland', 'flag' => 'poland.png']);
        DB::table('countrys')->insert(['country' => 'Portugal', 'flag' => 'portugal.png']);
        DB::table('countrys')->insert(['country' => 'Qatar', 'flag' => 'qatar.png']);
        DB::table('countrys')->insert(['country' => 'Romania', 'flag' => 'romania.png']);
        DB::table('countrys')->insert(['country' => 'Russia', 'flag' => 'russia.png']);
        DB::table('countrys')->insert(['country' => 'Rwanda', 'flag' => 'rwanda.png']);
        DB::table('countrys')->insert(['country' => 'Saint Kitts and Nevis', 'flag' => 'kn.png']);
        DB::table('countrys')->insert(['country' => 'Saint Lucia', 'flag' => 'saint_lucia.png']);
        DB::table('countrys')->insert(['country' => 'Samoa', 'flag' => 'samoa.png']);
        DB::table('countrys')->insert(['country' => 'San Marino', 'flag' => 'sm.png']);
        DB::table('countrys')->insert(['country' => 'Saudi Arabia', 'flag' => 'sa.png']);
        DB::table('countrys')->insert(['country' => 'Senegal', 'flag' => 'senegal.png']);
        DB::table('countrys')->insert(['country' => 'Serbia', 'flag' => 'serbia.png']);
        DB::table('countrys')->insert(['country' => 'Seychelles', 'flag' => 'seychelles.png']);
        DB::table('countrys')->insert(['country' => 'Sierra Leone', 'flag' => 'sl.png']);
        DB::table('countrys')->insert(['country' => 'Singapore', 'flag' => 'singapore.png']);
        DB::table('countrys')->insert(['country' => 'Slovakia', 'flag' => 'slovakia.png']);
        DB::table('countrys')->insert(['country' => 'Slovenia', 'flag' => 'slovenia.png']);
        DB::table('countrys')->insert(['country' => 'Solomon Islands', 'flag' => 'sb.png']);
        DB::table('countrys')->insert(['country' => 'Somalia', 'flag' => 'somalia.png']);
        DB::table('countrys')->insert(['country' => 'South Africa', 'flag' => 'za.png']);
        DB::table('countrys')->insert(['country' => 'South Korea', 'flag' => 'kr.png']);
        DB::table('countrys')->insert(['country' => 'South Sudan', 'flag' => 'ss.png']);
        DB::table('countrys')->insert(['country' => 'Spain', 'flag' => 'spain.png']);
        DB::table('countrys')->insert(['country' => 'Sri Lanka', 'flag' => 'lk.png']);
        DB::table('countrys')->insert(['country' => 'Sudan', 'flag' => 'sudan.png']);
        DB::table('countrys')->insert(['country' => 'Suriname', 'flag' => 'suriname.png']);
        DB::table('countrys')->insert(['country' => 'Swaziland', 'flag' => 'swaziland.png']);
        DB::table('countrys')->insert(['country' => 'Sweden', 'flag' => 'sweden.png']);
        DB::table('countrys')->insert(['country' => 'Switzerland', 'flag' => 'switzerland.png']);
        DB::table('countrys')->insert(['country' => 'Syria', 'flag' => 'syria.png']);
        DB::table('countrys')->insert(['country' => 'Tajikistan', 'flag' => 'tajikistan.png']);
        DB::table('countrys')->insert(['country' => 'Tanzania', 'flag' => 'tanzania.png']);
        DB::table('countrys')->insert(['country' => 'Thailand', 'flag' => 'thailand.png']);
        DB::table('countrys')->insert(['country' => 'Togo', 'flag' => 'togo.png']);
        DB::table('countrys')->insert(['country' => 'Tonga', 'flag' => 'tonga.png']);
        DB::table('countrys')->insert(['country' => 'Tunisia', 'flag' => 'tunisia.png']);
        DB::table('countrys')->insert(['country' => 'Turkey', 'flag' => 'turkey.png']);
        DB::table('countrys')->insert(['country' => 'Turkmenistan', 'flag' => 'turkmenistan.png']);
        DB::table('countrys')->insert(['country' => 'Tuvalu', 'flag' => 'tuvalu.png']);
        DB::table('countrys')->insert(['country' => 'Uganda', 'flag' => 'uganda.png']);
        DB::table('countrys')->insert(['country' => 'Ukraine', 'flag' => 'ukraine.png']);
        DB::table('countrys')->insert(['country' => 'United Arab Emirates', 'flag' => 'ae.png']);
        DB::table('countrys')->insert(['country' => 'United Kingdom', 'flag' => 'gb.png']);
        DB::table('countrys')->insert(['country' => 'United States', 'flag' => 'us.png']);
        DB::table('countrys')->insert(['country' => 'Uruguay', 'flag' => 'uy.png']);
        DB::table('countrys')->insert(['country' => 'Uzbekistan', 'flag' => 'uz.png']);
        DB::table('countrys')->insert(['country' => 'Vanuatu', 'flag' => 'vu.png']);
        DB::table('countrys')->insert(['country' => 'Venezuela', 'flag' => 've.png']);
        DB::table('countrys')->insert(['country' => 'Vietnam', 'flag' => 'vn.png']);
        DB::table('countrys')->insert(['country' => 'Yemen', 'flag' => 'ye.png']);
        DB::table('countrys')->insert(['country' => 'Zambia', 'flag' => 'zm.png']);
        DB::table('countrys')->insert(['country' => 'Zimbabwe', 'flag' => 'zw.png']);
    }
}
